Alistyle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from buyurtma.views import ProfilView, SettingView
from userapp.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', LoginView.as_view()),
    path('profil/', ProfilView.as_view()),
    path('setting/', SettingView.as_view()),
    path('user/', include("userapp.urls")),
    path('asosiy/', include("asosiy.urls")),
    path('buyurtma/', include("buyurtma.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asosiy/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('home/', HomeView.as_view()),
    path('bolimlar/', BolimlarView.as_view()),
    path('bolim/<int:pk>/', MahsulotlarView.as_view()),
    path('mahsulot/<int:pk>/', MahsulotView.as_view(), name='mahsulot_id'),

]

asosiy/models.py
from django.db import models
from userapp.models import Profil


class Bolim(models.Model):
    nom = models.CharField(max_length=30)
    rasm = models.FileField(upload_to="bolimlar")

    def __str__(self):
        return self.nom


class Mahsulot(models.Model):
    nom = models.CharField(max_length=30)
    narx = models.PositiveSmallIntegerField()
    brend = models.CharField(max_length=30)
    chegirma = models.PositiveSmallIntegerField(default=0)
    batafsil = models.TextField()
    kafolat = models.CharField(max_length=50)
    yetkazish = models.CharField(max_length=30)
    mavjud = models.BooleanField(default=True)
    davlat = models.CharField(max_length=30)
    bolim = models.ForeignKey(Bolim, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.nom} & {self.brend}"


class Media(models.Model):
    rasm = models.FileField(upload_to="Mahsulot")
    mahsulot = models.ForeignKey(Mahsulot, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.mahsulot}"


class Izoh(models.Model):
    profil = models.ForeignKey(Profil, on_delete=models.SET_NULL, null=True)
    mahsulot = models.ForeignKey(Mahsulot, on_delete=models.SET_NULL, null=True)
    matn = models.TextField()
    baho = models.PositiveSmallIntegerField(default=5)
    sana = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.profil} & {self.mahsulot}"

templates/header.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% load static %}
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="Bootstrap e-commerce html template similar to Alibaba">
    <meta name="keywords" content="Online template, shop, theme, template, html, css, bootstrap 4">

    <title>Website title - bootstrap alistyle html template</title>

    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css"/>

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

</head>
<body>

<!-- REMOVE FOLLOWING LINK -->
<a href="http://bootstrap-ecommerce.com/page-themes.html" class="btn btn-dark rounded-pill"
   style="font-size:13px; z-index:100; position: fixed; bottom:10px; right:10px;">Download theme</a>
<!-- REMOVE  //END -->


<header class="section-header">
    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-2 col-lg-3 col-md-12">

                    <a href="http://bootstrap-ecommerce.com" class="brand-wrap">
                        <img class="logo" src="/media/misc/logo.png/">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-xl-6 col-lg-5 col-md-6">
                    <form action="#" class="search-header">
                        <div class="input-group w-100">
                            <select class="custom-select border-right" name="category_name">
                                <option value="">All type</option>
                                <option value="codex">Special</option>
                                <option value="comments">Only best</option>
                                <option value="content">Latest</option>
                            </select>
                            <input type="text" class="form-control" placeholder="Search">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i> Search
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-xl-4 col-lg-4 col-md-6">
                    <div class="widgets-wrap float-md-right">
                        <div class="widget-header mr-3">
                            <a href="#" class="widget-view">
                                <div class="icon-area">
                                    <i class="fa fa-user"></i>
                                </div>
                                <small class="text"> Profil </small>
                            </a>
                        </div>

                        <div class="widget-header mr-3">
                            <a href="/buyurtma/buyurtmalar/" class="widget-view">
                                <div class="icon-area">
                                    <i class="fa fa-store"></i>
                                </div>
                                <small class="text"> Buyurtmalar </small>
                            </a>
                        </div>
                        <div class="widget-header">
                            <a href="/buyurtma/savatlar/" class="widget-view">
                                <div class="icon-area">
                                    <i class="fa fa-shopping-cart"></i>
                                </div>
                                <small class="text"> Savatlar </small>
                            </a>
                        </div>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->


</header> <!-- section-header.// -->


{% block content %}

{% endblock %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-secondary">
    <div class="container">


        <section class="footer-bottom text-center">

            <p class="text-white">" Onlayn shop " </p>
            <p class="text-muted"> &copy 2023 TATU Fergana </p>
            <br>
        </section>
    </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

</body>
</html>

templates/page-detail-product.html
{% extends 'header.html' %}

{% block content %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">
    <div class="container">
        <!-- ============================ ITEM DETAIL ======================== -->
        <div class="row">
            <aside class="col-md-6">
                <div class="card">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div><a href="#"><img src="{{ mahsulot.media_set.first.rasm.url }}"></a></div>
                        </div> <!-- slider-product.// -->
                        <div class="thumbs-wrap">
                            {% for media in mahsulot.media_set.all|slice:"1:6" %}
                            <a href="#" class="item-thumb"> <img src="{{ media.rasm.url }}"></a>
                            {% endfor %}
                        </div> <!-- slider-nav.// -->
                    </article> <!-- gallery-wrap .end// -->
                </div> <!-- card.// -->
            </aside>
            <main class="col-md-6">
                <article class="product-info-aside">
                    <h2 class="title mt-3">{{ mahsulot.nom }} </h2>
                    <div class="rating-wrap my-3">
                        <ul class="rating-stars">
                            <li style="width:{{ ortachasi }}%" class="stars-active">
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                        </ul>
                        <small class="label-rating text-muted">{{ mahsulot.izoh_set.count }} Izohlar</small>
                        <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i>
                        </small>
                    </div> <!-- rating-wrap.// -->
                    <div class="mb-3">
                        <var class="price h4">{{ mahsulot.narx }} so'm</var>
                        <span class="text-muted">{{ mahsulot.chegirma }}% chegirma</span>
                    </div> <!-- price-detail-wrap .// -->
                    <p>{{ mahsulot.batafsil }} </p>
                    <dl class="row">
                        <dt class="col-sm-3">Ishlab chiqaruvchi</dt>
                        <dd class="col-sm-9"><a href="#">{{ mahsulot.brend }}</a></dd>

                        <dt class="col-sm-3">Kafolat</dt>
                        <dd class="col-sm-9">{{ mahsulot.kafolat }}</dd>

                        <dt class="col-sm-3">Yetkazib berish vaqti</dt>
                        <dd class="col-sm-9">{{ mahsulot.yetkazish }}</dd>

                        <dt class="col-sm-3">Do'konda</dt>
                        {% if mahsulot.mavjud %}
                        <dd class="col-sm-9">Mavjud</dd>
                        {% else %}
                        <dd class="col-sm-9">Mavjud emas</dd>
                        {% endif %}
                    </dl>
                    <div class="form-row  mt-4">

                        <div class="form-group col-md">
                            <a href="/buyurtma/item_qosh/{{ mahsulot.id }}" class="btn  btn-primary">
                                <i class="fas fa-shopping-cart"></i> <span class="text">Savatchaga qo'shish</span>
                            </a>
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->

                </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->

        <!-- ================ ITEM DETAIL END .// ================= -->

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<div class="container d-flex justify-content-center align-items-center">
    <form method="post"> {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputComment1">Sizning fikringiz</label>

            <div class="rating-container d-flex" id="smileyRating" style="gap: 20px;">
                <input type="radio" name="baho" value="1" id="smiley1" style="display:none;">
                <label class="smiley-face" for="smiley1" style="cursor: pointer">&#9785;</label>
                <input type="radio" name="baho" value="2" id="smiley2" style="display:none;">
                <label class="smiley-face" for="smiley2" style="cursor: pointer">&#x1F610;</label>
                <input type="radio" name="baho" value="3" id="smiley3" style="display:none;" checked>
                <label class="smiley-face" for="smiley3" style="cursor: pointer">&#x1F642;</label>
                <input type="radio" name="baho" value="4" id="smiley4" style="display:none;">
                <label class="smiley-face" for="smiley4" style="cursor: pointer">&#x1F600;</label>
                <input type="radio" name="baho" value="5" id="smiley5" style="display:none;">
                <label class="smiley-face" for="smiley5" style="cursor: pointer">&#x1F929;</label>
            </div>
        </div>
        <div class="form-group">
            <input type="text" class="form-control" id="exampleInputComment1" aria-describedby="commentHelp"
                   placeholder="Enter your comment" name="matn">
        </div>
        <button type="submit" class="btn btn-primary">Izoh qo'shish</button>
    </form>

    <div id="selectedRating"></div>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            var smileyFaces = document.querySelectorAll('.smiley-face');

            smileyFaces.forEach((face) => {
              face.addEventListener('click', () => {
                // reset transform of all smiley faces
                smileyFaces.forEach((face) => {
                  face.style.transform = "none"; // add !important if necessary
                });
                // scale up the clicked smiley face
                face.style.transform = "scale(2)"; // add !important if necessary
              });
            });
          });
    </script>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center mb-4">Izohlar</h2>
            <hr>
            {% for izoh in mahsulot.izoh_set.all %}
            <div class="row">
                <div class="col-sm-2">
                    <div class="text-center">
                        {% if izoh.baho == 1 %}
                        <span class="smiley-face">&#9785;</span>
                        {% elif izoh.baho == 2 %}
                        <span class="smiley-face">&#x1F610;</span>
                        {% elif izoh.baho == 3 %}
                        <span class="smiley-face">&#x1F642;</span>
                        {% elif izoh.baho == 4 %}
                        <span class="smiley-face">&#x1F600;</span>
                        {% elif izoh.baho == 5 %}
                        <span class="smiley-face">&#x1F929;</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-10">
                    <p>{{ izoh.matn }}</p>
                    <div class="user d-flex" style="gap: 300px">
                        <p><small class="text-muted">{{ izoh.sana }}</small></p>
                        <p><small class="text-muted">{{ izoh.profil.first_name }} {{ izoh.profil.last_name }}</small>
                        </p>
                    </div>
                </div>
            </div>
            <hr>
            {% empty %}
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

templates/page-index-2.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css"/>

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}'" type="text/javascript"></script>

</head>
<body>

<!-- REMOVE FOLLOWING LINK -->
<a href="http://bootstrap-ecommerce.com/page-themes.html" class="btn btn-dark rounded-pill"
   style="font-size:13px; z-index:100; position: fixed; bottom:10px; right:10px;">Download theme</a>
<!-- REMOVE  //END -->

<header class="section-header">
    <nav class="navbar d-none d-md-flex p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTop4">
                <ul class="navbar-nav mr-auto">

                </ul>
                <ul class="navbar-nav">

                    <li><span class="nav-link">Hi, <a href="/user/login/"> Sign in </a> </span>
                    <li><span class="nav-link"><a href="/user/register/"> Register </a></span>

                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
        </div> <!-- container //  -->
    </nav>

    <div class="container">
        <section class="header-main border-bottom">
            <div class="row row-sm">
                <div class="col-6 col-sm col-md col-lg  flex-grow-0">
                    <a href="http://bootstrap-ecommerce.com" class="brand-wrap">
                        <img class="logo" src="/media/misc/logo.png/">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-6 col-sm col-md col-lg flex-md-grow-0">

                    <!-- mobile-only -->
                    <div class="d-md-none float-right">
                        <a href="#" class="btn btn-light"> <i class="fa fa-bell"></i> </a>
                        <a href="#" class="btn btn-light"> <i class="fa fa-user"></i> </a>
                        <a href="#" class="btn btn-light"> <i class="fa fa-shopping-cart"></i> 2 </a>
                    </div>
                    <!-- mobile-only //end  -->

                    <div class="category-wrap d-none dropdown d-md-inline-block">
                        <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown"> Onlayn Shop
                        </button>
                    </div>  <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <div class="col-lg-6 col-xl col-md-5 col-sm-12 flex-grow-1">
                    <form action="#" class="search-header">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <select class="custom-select border-left" name="category_name">
                                <option value="">All type</option>
                                <option value="codex">Special</option>
                                <option value="comments">Only best</option>
                                <option value="content">Latest</option>
                            </select>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col col-lg col-md flex-grow-0">
                    <button class="btn btn-block btn-primary" type="submit"> Search</button>
                </div>
                <div class="col col-lg col-md flex-grow-0">
                    <button class="btn btn-block btn-light" type="submit"> Advanced</button>
                </div>
            </div> <!-- row.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand pl-0">
            <ul class="navbar-nav flex-wrap">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> Demo pages </a>
                    <div class="dropdown-menu dropdown-large">
                        <nav class="row">
                            <div class="col-6">
                                <a href="page-index-1.html">Home page 1</a>
                                <a href="page-index-2.html">Home page 2</a>
                                <a href="page-category.html">All category</a>
                                <a href="page-listing-large.html">Listing list</a>
                                <a href="page-listing-grid.html">Listing grid</a>
                                <a href="page-shopping-cart.html">Shopping cart</a>
                                <a href="page-detail-product.html">Product detail</a>
                                <a href="page-content.html">Page content</a>
                                <a href="page-user-login.html">Page login</a>
                                <a href="page-user-register.html">Page register</a>
                            </div>
                            <div class="col-6">
                                <a href="page-profile-main.html">Profile main</a>
                                <a href="page-profile-orders.html">Profile orders</a>
                                <a href="page-profile-seller.html">Profile seller</a>
                                <a href="page-profile-wishlist.html">Profile wishlist</a>
                                <a href="page-profile-setting.html">Profile setting</a>
                                <a href="page-profile-address.html">Profile address</a>
                                <a href="page-components.html" target="_blank">More components</a>
                            </div>
                        </nav> <!--  row end .// -->
                    </div> <!--  dropdown-menu dropdown-large end.// -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Electronics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Fashion</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Beauty</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Motors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sports</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Gardening</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Deals</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Under $10</a>
                </li>
            </ul>
        </nav> <!-- navbar-main  .// -->

    </div> <!-- container.// -->
</header> <!-- section-header.// -->

<br>
<hr>
<br>

<div class="container">

    <!-- =============== SECTION 1 =============== -->
    <section class="padding-bottom">
        <header class="section-heading mb-4">
            <h3 class="title-section">Hamma mahsulotlar</h3>
        </header>

        <div class="row">
            {% for mahsulot in mahsulotlar %}
            <div class="col-xl-3 col-lg-3 col-md-4 col-6">
                <div class="card card-product-grid">
                    <a href="#" class="img-wrap"> <img src="{{ mahsulot.media_set.first.rasm.url }}"> </a>
                    <figcaption class="info-wrap">

                        <div>
                            <a href="#" class="text-muted">{{ mahsulot.nom }}</a>
                            <a href="#" class="title">{{ mahsulot.nom }}</a>
                        </div>
                        <div class="price h5 mt-2">{{ mahsulot.narx }} so'm</div> <!-- price.// -->
                    </figcaption>
                </div>
            </div> <!-- col.// -->
            {% endfor %}

        </div> <!-- row.// -->
    </section>
    <!-- =============== SECTION 1 END =============== -->

    <br>
    <br>
    <hr>
    <hr>
    <hr>
    <br>
    <br>
    <!-- =============== SECTION 2 =============== -->
    <section class="padding-bottom">

        <header class="section-heading mb-4">
            <h3 class="title-section">Chegirmalik mahsulotlar</h3>
        </header>

        <div class="row row-sm">
            {% for mahsulot in chegirmali_mahsulotlar %}
            <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                <div href="#" class="card card-sm card-product-grid">
                    <a href="/asosiy/mahsulot/{{ mahsulot.id }}/" class="img-wrap">
                        <b class="badge badge-danger mr-1"> -{{ mahsulot.chegirma }} %</b>
                        <img src="{{ mahsulot.media_set.first.rasm.url }}">
                    </a>
                    <figcaption class="info-wrap">
                        <a href="#" class="title">{{ mahsulot.nom }}</a>
                        <div class="price-wrap">
                            <del class="price-old">{{ mahsulot.narx }} so'm</del>
                            <br>
                            <span class="price">{{ mahsulot.narx }} so'm</span>
                        </div> <!-- price-wrap.// -->
                    </figcaption>
                </div>
            </div> <!-- col.// -->
            {% endfor %}


        </div> <!-- row.// -->
    </section>
    <!-- =============== SECTION 2 END =============== -->


    <!-- =============== SECTION BANNER =============== -->
    <section class="padding-bottom">
        <article class="box d-flex flex-wrap align-items-center p-5 bg-secondary">
            <div class="text-white mr-auto">
                <h3>Mahsulotlarni ko'rmoqchimisiz? </h3>
                <p> Login va parol orqali tizimga kiring !!! </p>
            </div>
            <div class="mt-3 mt-md-0"><a href="/user/login/" class="btn btn-outline-light">Tizimga kirish</a></div>
        </article>
    </section>
    <!-- =============== SECTION BANNER .//END =============== -->

</div>
<!-- container end.// -->

</body>
</html>

templates/page-profile-wishlist.html
{% extends 'header.html' %}

{% block content %}


<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg-gray">
    <div class="container">
        <h2 class="title-page">Tanlanganlar</h2>
    </div> <!-- container //  -->
</section>
<!-- ========================= SECTION PAGETOP END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <nav class="list-group">
                    <a class="list-group-item" href="/profil/"> Profil </a>
                    <a class="list-group-item" href="/buyurtma/buyurtmalar/"> Buyurtmalar </a>
                    <a class="list-group-item active" href="/buyurtma/tanlanganlar/"> Tanlanganlar </a>
                    <a class="list-group-item" href="/setting/"> Sozlamalar </a>
                    <a class="list-group-item" href="/user/logout/"> Log out </a>
                </nav>
            </aside> <!-- col.// -->
            <main class="col-md-9">
                <article class="card">
                    <div class="card-body">
                        <div class="row">
                            {% for tanlangan in tanlanganlar %}
                            <div class="col-md-6">
                                <figure class="itemside mb-4">
                                    <div class="aside"><img src="{{ tanlangan.mahsulot.media_set.first.rasm.url }}"
                                                            class="border img-md"></div>
                                    <figcaption class="info">
                                        <a href="/asosiy/mahsulot/{{ tanlangan.mahsulot.id}}/" class="title">Nomi : {{
                                            tanlangan.mahsulot.nom }}</a>
                                        <p class="price mb-2">Brend : {{ tanlangan.mahsulot.brend }}</p>
                                        <p class="price mb-2">Summa : {{ tanlangan.mahsulot.narx }}</p>
                                        <a href="/buyurtma/item_qosh/{{ tanlangan.mahsulot.id }}/"
                                           class="btn btn-secondary btn-sm"> Savatchaga qo'shish </a>
                                        <a href="/buyurtma/t_ochir/{{ tanlangan.id }}/" class="btn btn-danger btn-sm"
                                           data-toggle="tooltip" title="" data-original-title="Remove from wishlist"> <i
                                                class="fa fa-times"></i> </a>
                                    </figcaption>
                                </figure>
                            </div> <!-- col.// -->
                            {% endfor %}
                        </div> <!-- row .//  -->
                    </div> <!-- card-body.// -->
                </article>
            </main> <!-- col.// -->
        </div>
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock%}